package tz.go.roadsfund.nrcc.enums;

/**
 * User roles in the NRCC system
 */
public enum UserRole {
    PUBLIC_APPLICANT,
    MEMBER_OF_PARLIAMENT,
    REGIONAL_ROADS_BOARD_INITIATOR,
    REGIONAL_ADMINISTRATIVE_SECRETARY,
    REGIONAL_COMMISSIONER,
    MINISTER_OF_WORKS,
    NRCC_CHAIRPERSON,
    NRCC_MEMBER,
    NRCC_SECRETARIAT,
    MINISTRY_LAWYER,
    SYSTEM_ADMINISTRATOR
}
